### ISSUE TITLE
Support for async helper results used as argument for another helper.

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/helper-cache#3]
@kpdecker - This is a simplified use case of how we're using async helpers with handlebars templates. We also use them for rendering smaller pieces of content that may require some async processing before returning to the parent template. With your experience in Handlebars and other templating engines, do you see where we can improve this and possible get them working with subexpressions?

---
Due to how async helpers generate a temporary ID, then replace that ID when the helper is resolved, they cannot be used as arguments to other helpers:

- Handlebars

```handlebars
{{#iterate (fetch "http://example.com/items.json")}}
...
{{/iterate}}
```

- Lodash

```html
<%= iterate(fetch("http://example.com/items.json"), itemTemplate) %>
```

Where `fetch` retrieves data from an external server and is async:

```js
module.exports = fetch (src, options, next) {
  if (typeof options === 'function') {
    next = options;
    options = {};
  }
  request.get(src, function (err, results) {
    if (err) return next(err);
    next(null, JSON.parse(results));
  });
};
```

And `iterate` does something with the fetched results.

**Comment by kpdecker** [comment]
The key thing with subexpressions is the asynchrony will have to block the execution of the helper until all subexpressions are resolved. The implementation of `fetch` looks like one that I would expect, but the the complexity is going to lay in the having some sort of scheduler for these calls all all the way down to the helper level. The few times that I've considered this, it always ended up with pretty invasive changes within the core of the language runtime itself.

**Comment by doowb** [comment]
We moved async helpers to [async-helpers](https://github.com/doowb/async-helpers) and added a way to handle subexpressions. It's still all processed post render so we can use it in different template engines.
